<a href="https://colab.research.google.com/github/Sathvara-Amitkumar/CNN_DL/blob/main/MNIST_image_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

warnings.filterwarnings('ignore')

In [20]:
cd /content/drive/MyDrive/Colab Notebooks/CNN

/content/drive/MyDrive/Colab Notebooks/CNN

In [21]:
ls

MNIST_image_classification.ipynb  mnist_test.csv  mnist_train.csv

In [22]:
df = pd.read_csv("mnist_train.csv")
df_test = pd.read_csv("mnist_test.csv")

In [23]:
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df_test.shape

(10000, 785)

In [28]:
df.shape

(60000, 785)

In [29]:
df.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [30]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [46]:
df.sample(5)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
26224,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33809,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24797,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31496,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51658,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
# Preprocess Data

x_train = df.drop('label', axis=1).values
y_train = df['label'].values
x_test = df_test.drop('label', axis=1).values
y_test = df_test['label'].values

In [49]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0