<a href="https://colab.research.google.com/github/Sathvara-Amitkumar/CNN_DL/blob/main/MNIST_image_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

warnings.filterwarnings('ignore')

In [6]:
cd /content/drive/MyDrive/Colab Notebooks/CNN

/content/drive/MyDrive/Colab Notebooks/CNN

In [7]:
ls

MNIST_image_classification.ipynb  mnist_test.csv  mnist_train.csv

In [8]:
df = pd.read_csv("mnist_train.csv")
df_test = pd.read_csv("mnist_test.csv")

In [9]:
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_test.shape

(10000, 785)

In [11]:
df.shape

(60000, 785)

In [12]:
df.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [13]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [14]:
df.sample(5)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
26710,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38394,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32203,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6396,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40972,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# Preprocess Data

x_train = df.drop('label', axis=1).values
y_train = df['label'].values
x_test = df_test.drop('label', axis=1).values
y_test = df_test['label'].values

In [16]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [18]:
# x_train_img = x_train.reshape(x_train.shape[0], 28, 28, 1)
# x_test_img = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [19]:
x_train_img = x_train.reshape(-1, 28, 28)
x_test_img = x_test.reshape(-1, 28, 28)

-1: Yeh Python ko batata hai ki 'number of samples' ko automatic calculate kar lo.

28, 28: Yeh phir se har image ki height aur width hai, jo ki 28 by 28 pixels hai.

In [20]:
x_train_img

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)

In [21]:
x_train_img.shape

(60000, 28, 28)

In [22]:
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

# **Perceptron**

In [23]:
perceptron = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation='softmax')
])

In [24]:
perceptron.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [28]:
history_perceptron = perceptron.fit(x_train_img, y_train_cat, epochs=10, batch_size=32,
                                    validation_data=(x_test_img, y_test_cat), verbose=2)

Epoch 1/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9117 - loss: 0.3172 - val_accuracy: 0.9159 - val_loss: 0.3037
Epoch 2/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9125 - loss: 0.3135 - val_accuracy: 0.9169 - val_loss: 0.3001
Epoch 3/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9141 - loss: 0.3103 - val_accuracy: 0.9187 - val_loss: 0.2978
Epoch 4/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9141 - loss: 0.3075 - val_accuracy: 0.9176 - val_loss: 0.2951
Epoch 5/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9148 - loss: 0.3049 - val_accuracy: 0.9184 - val_loss: 0.2941
Epoch 6/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9157 - loss: 0.3025 - val_accuracy: 0.9180 - val_loss: 0.2921
Epoch 7/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9164 - loss: 0.3004 - val_accuracy: 0.9188 - val_loss: 0.2905
Epoch 8/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9171 - loss: 0.2986 - val_accuracy: 0.9188 - val_loss: 0.2897
Epoch 9/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9173 - loss: 0.2966 - val_accuracy: 0.9188 - val_loss: 0.2893
Epoch 10/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9176 - loss: 0.2950 - val_accuracy: 0.9197 - val_loss: 0.2873

In [29]:
accuracy_perceptron = perceptron.evaluate(x_test_img, y_test_cat)[1]
print(f"Accuracy of Perceptron: {accuracy_perceptron * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9197 - loss: 0.2873
Accuracy of Perceptron: 91.97%

# **ANN**

In [30]:
ann = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [31]:
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [32]:
history_ann = ann.fit(x_train_img, y_train_cat, epochs=10, batch_size=32,
                      validation_data=(x_test_img, y_test_cat), verbose=1)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9301 - loss: 0.2402 - val_accuracy: 0.9580 - val_loss: 0.1344
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9697 - loss: 0.0996 - val_accuracy: 0.9706 - val_loss: 0.0925
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9784 - loss: 0.0701 - val_accuracy: 0.9745 - val_loss: 0.0809
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9831 - loss: 0.0540 - val_accuracy: 0.9716 - val_loss: 0.0951
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9860 - loss: 0.0427 - val_accuracy: 0.9774 - val_loss: 0.0847
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9876 - loss: 0.0359 - val_accuracy: 0.9748 - val_loss: 0.0917
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9913 - loss: 0.0272 - val_accuracy: 0.9769 - val_loss: 0.0888
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9909 - loss: 0.0258 - val_accuracy: 0.9749 - val_loss: 0.1027
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9930 - loss: 0.0209 - val_accuracy: 0.9779 - val_loss: 0.0924
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9937 - loss: 0.0186 - val_accuracy: 0.9762 - val_loss: 0.1001

In [33]:
accuracy_ann = ann.evaluate(x_test_img, y_test_cat)[1]
print(f"Accuracy of ANN: {accuracy_ann * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9762 - loss: 0.1001
Accuracy of ANN: 97.62%

# **CNN**

In [39]:
x_train_cnn = x_train.reshape(-1, 28, 28, 1)
x_test_cnn = x_test.reshape(-1, 28, 28, 1)

In [42]:
cnn = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

In [43]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [44]:
history_cnn = cnn.fit(x_train_cnn, y_train_cat, epochs=5, batch_size=32,
                     validation_data=(x_test_cnn, y_test_cat), verbose=1)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9336 - loss: 0.2209 - val_accuracy: 0.9859 - val_loss: 0.0455
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9757 - loss: 0.0827 - val_accuracy: 0.9895 - val_loss: 0.0329
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9826 - loss: 0.0589 - val_accuracy: 0.9904 - val_loss: 0.0290
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9851 - loss: 0.0488 - val_accuracy: 0.9895 - val_loss: 0.0332
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9880 - loss: 0.0401 - val_accuracy: 0.9910 - val_loss: 0.0270

In [45]:
accuracy_cnn = cnn.evaluate(x_test_cnn, y_test_cat)[1]
print(f"Accuracy of CNN: {accuracy_cnn * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9910 - loss: 0.0270
Accuracy of CNN: 99.10%