<a href="https://colab.research.google.com/github/Sathvara-Amitkumar/CNN_DL/blob/main/MNIST_image_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

warnings.filterwarnings('ignore')

In [2]:
cd /content/drive/MyDrive/Colab Notebooks/CNN

/content/drive/MyDrive/Colab Notebooks/CNN

In [3]:
ls

MNIST_image_classification.ipynb  mnist_test.csv  mnist_train.csv

In [4]:
df = pd.read_csv("mnist_train.csv")
df_test = pd.read_csv("mnist_test.csv")

In [5]:
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_test.shape

(10000, 785)

In [7]:
df.shape

(60000, 785)

In [8]:
df.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [9]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [10]:
df.sample(5)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
3210,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19588,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23023,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45382,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13158,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# Preprocess Data

x_train = df.drop('label', axis=1).values
y_train = df['label'].values
x_test = df_test.drop('label', axis=1).values
y_test = df_test['label'].values

In [12]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [23]:
# x_train_img = x_train.reshape(x_train.shape[0], 28, 28, 1)
# x_test_img = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [24]:
x_train_img = x_train.reshape(-1, 28, 28)
x_test_img = x_test.reshape(-1, 28, 28)

-1: Yeh Python ko batata hai ki 'number of samples' ko automatic calculate kar lo.

28, 28: Yeh phir se har image ki height aur width hai, jo ki 28 by 28 pixels hai.

In [25]:
x_train_img

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)

In [26]:
x_train_img.shape

(60000, 28, 28)

In [27]:
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

# Perceptron

In [30]:
perceptron = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation='softmax')
])

In [31]:
perceptron.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [32]:
history_perceptron = perceptron.fit(x_train_img, y_train_cat, epochs=10, batch_size=32,
                                    validation_data=(x_test_img, y_test_cat), verbose=2)

Epoch 1/10
1875/1875 - 4s - 2ms/step - accuracy: 0.8121 - loss: 0.7850 - val_accuracy: 0.8831 - val_loss: 0.4794
Epoch 2/10
1875/1875 - 4s - 2ms/step - accuracy: 0.8812 - loss: 0.4551 - val_accuracy: 0.8971 - val_loss: 0.4000
Epoch 3/10
1875/1875 - 5s - 3ms/step - accuracy: 0.8918 - loss: 0.4026 - val_accuracy: 0.9019 - val_loss: 0.3681
Epoch 4/10
1875/1875 - 5s - 3ms/step - accuracy: 0.8972 - loss: 0.3763 - val_accuracy: 0.9062 - val_loss: 0.3487
Epoch 5/10
1875/1875 - 4s - 2ms/step - accuracy: 0.9007 - loss: 0.3596 - val_accuracy: 0.9099 - val_loss: 0.3357
Epoch 6/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9043 - loss: 0.3479 - val_accuracy: 0.9114 - val_loss: 0.3267
Epoch 7/10
1875/1875 - 5s - 2ms/step - accuracy: 0.9064 - loss: 0.3389 - val_accuracy: 0.9122 - val_loss: 0.3199
Epoch 8/10
1875/1875 - 4s - 2ms/step - accuracy: 0.9078 - loss: 0.3319 - val_accuracy: 0.9151 - val_loss: 0.3137
Epoch 9/10
1875/1875 - 4s - 2ms/step - accuracy: 0.9094 - loss: 0.3260 - val_accuracy: 0.9148 - val_loss: 0.3103
Epoch 10/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9109 - loss: 0.3211 - val_accuracy: 0.9165 - val_loss: 0.3063

In [33]:
accuracy_perceptron = perceptron.evaluate(x_test_img, y_test_cat)[1]
print(f"Accuracy of Perceptron: {accuracy_perceptron * 100:.2f}%")

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9165 - loss: 0.3063
Accuracy of Perceptron: 91.65%